/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Question11;

/**
 *
 * @author Harshavardhan Kurra
 */
public class BankDriver {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("Answer for question 11: Harshavardhan Kurra");
        Bank bank1 = new Bank(1524,"us bank", 9000);  // create instance bank1 of Bank class
        Bank bank2 = new Bank(6546, "chase bank", 8000); // create instance bank2 of Bank class
        Bank bank3= new Bank(6757, "icici bank", 5000);  // create instance bank3 of Bank class

        System.out.println(bank1.equals(bank2));  //check for equals comparision of bank1 and bank2 objects
        System.out.println(bank2.equals(bank3));  //check for equals comparision of bank2 and bank3 objects
        System.out.println(bank1.equals(bank3));  //check for equals comparision of bank1 and bank3 objects
        System.out.println("Hash code of bank1: " + bank1.hashCode());  //prints the hashcode generated by bank1 object
        System.out.println("Hash code of bank2: " + bank2.hashCode());  //prints the hashcode generated by bank2 object
        System.out.println("Hash code of bank3: " + bank3.hashCode());  //prints the hashcode generated by bank3 object
    }
    
}
